server.port=8084
spring.application.name=auth-service

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# JWT Configuration
# A chave deve ter pelo menos 256 bits (32 caracteres)
jwt.secret=GasStationHubSuperSecretKeyForJwtAuthentication2026!
jwt.expiration=300000
jwt.refreshExpiration=86400000
