spring.application.name=loyalty-service
server.port=8082
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Configuração do PostgreSQL (R2DBC e Inicialização)
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/loyalty_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.sql.init.mode=always

# Observabilidade (Actuator + Micrometer Tracing)
management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=loyalty-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
