spring.application.name=supply-service
server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gasstation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
