spring.application.name=supply-service
server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gasstation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=always

# Configurações do Resilience4J - Circuit Breaker
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.sliding-window-size=4
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.loyaltyCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

# Observabilidade (Actuator + Micrometer Tracing)
management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JWT Configuration
jwt.secret=GasStationHubSuperSecretKeyForJwtAuthentication2026!

logging.level.org.springframework.security=TRACE
